window:
  dimensions:
    columns: 100
    lines: 24
  opacity: 0.8
  decorations: None
font:
  size: 11
  builtin_box_drawing: true
  normal:
    family: DejaVuSansMono Nerd Font
    style: Regular
  bold:
    family: DejaVuSansMono Nerd Font
    style: Bold
  italic:
    family: DejaVuSansMono Nerd Font
    style: Oblique
  glyph_offset:
    x: 0
    y: 0
scrolling:
  history: 10000
  multiplier: 3
custom_cursor_colors: true
draw_bold_text_with_bright_colors: false

colors:
  normal:
        black:   '0xffffff'
        red:     '0xc82829'
        green:   '0x00af64'
        yellow:  '0xeab700'
        blue:    '0x006faf'
        magenta: '0x8939a8'
        cyan:    '0x00afaf'
        white:   '0x4d4d4c'

key_bindings:
  - { Key: V,     mods: Control,      action: Paste         }
  - { Key: C,     mods: Control,      action: Copy          }
  - { Key: Q,     mods: Control,      action: Quit          }
  - { Key: N,     mods: Control,      action: SpawnNewInstance}
  - { Key: C,     mods: Control|Shift,chars: "\x03"         }


cursor:
  style: Beam
  unfocused_hollow: true
  live_config_reload: true

